### ISSUE TITLE
Module does not support secured server

### ISSUE THREAD

**Issue by roi007leaf** [LebombJames/random-folder-colours#2]
![image](https://user-images.githubusercontent.com/17231451/204072031-f2ca7be6-d1d7-4d95-a6c2-0f6dd0ac2f0f.png)

**Comment by LebombJames** [comment]
Well this is what I get for only testing on my local server 🙃

**Comment by roi007leaf** [comment]
Lol I know what you mean, developer myself XD

**Comment by averrin** [comment]
Yeah, it's blocker for Forge =(

**Comment by LebombJames** [comment]
Unfortunately after some investigation, it doesn't seem like I am able to work around this. Colormind uses HTTP, and Chrome forbids HTTP running on HTTPS servers. I have emailed the owner of Colormind about it, but until then there is nothing I can do I'm afraid.
