### ISSUE TITLE
Trying to set random colors on file folders errors out

### ISSUE THREAD

**Issue by cgplayer2000** [LebombJames/random-folder-colours#3]
I suspect this error might be related to Issue #2 but I'll list it anyway.  My Foundry instance is hosted on the Forge and I cannot get this module to work.  I use Chrome as well.  
![image](https://user-images.githubusercontent.com/10798879/215309994-47ebb429-d538-4e3b-a2fe-7f6b75551275.png)

**Comment by LebombJames** [comment]
This is the same issue as #2, the error message is just different because the module uses a different API now
